issuer: http://127.0.0.1:30001
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
   http: 0.0.0.0:30001

expiry:
  signingKeys: "10m"
  idTokens: "30m"

logger:
  level: "debug"
  format: "json" 

oauth2:
  responseTypes: ["code", "token", "id_token"]
  skipApprovalScreen: true

connectors:
- type: mockCallback
  id: mock
  name: Example

staticClients:
- id: example-cluster-client-id
  name: Kubernetes Dev Cluster
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0 
  redirectURIs:
    - http://127.0.0.1:30002/callback/example-cluster

enablePasswordDB: True

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"  